name: Windows Build

on:
  push:
    branches:
      - master

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\DALTools\DALTools.sln

jobs:
  build:
    name: ${{matrix.configuration}}
    runs-on: windows-2019
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.configuration}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: DALTools-${{matrix.configuration}}
        path:  |
          ${{env.GITHUB_WORKSPACE}}\DALTools\DALLib\bin\${{matrix.configuration}}\DALLib.dll
          ${{env.GITHUB_WORKSPACE}}\DALTools\PCKTool\bin\${{matrix.configuration}}\PCKTool.exe
          ${{env.GITHUB_WORKSPACE}}\DALTools\STSCTool\bin\${{matrix.configuration}}\STSCTool.exe
          ${{env.GITHUB_WORKSPACE}}\DALTools\TEXTool\bin\${{matrix.configuration}}\TEXTool.exe
          ${{env.GITHUB_WORKSPACE}}\DALTools\FontEditor\bin\${{matrix.configuration}}\FontEditor.exe
          ${{env.GITHUB_WORKSPACE}}\DALTools\ScriptDatabaseEditor\bin\${{matrix.configuration}}\ScriptDatabaseEditor.exe
          ${{env.GITHUB_WORKSPACE}}\DALTools\ScriptDialogueEditor\bin\${{matrix.configuration}}\ScriptDialogueEditor.exe
          ${{env.GITHUB_WORKSPACE}}\DALTools\TableEditor\bin\${{matrix.configuration}}\TableEditor.exe
